version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis
      - db
  worker:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DB=pdf_processor_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
